# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteAccount():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteAccount(self):
    self.driver.get("https://sproj-prototype1.vercel.app/")
    self.driver.set_window_size(1536, 837)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("saad.khilji@hotmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("Saad2003!")
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Aw-1\\/2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-3").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-red-500").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border").send_keys("delete")
    time.sleep(6)
    self.driver.find_element(By.CSS_SELECTOR, ".bg-red-600").click()
  
