# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPastPaper():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_pastPaper(self):
    self.driver.get("https://sproj-prototype1.vercel.app/")
    self.driver.set_window_size(1536, 837)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("saad.khilji@hotmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("Saad2003@")
    self.driver.find_element(By.CSS_SELECTOR, ".py-3").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Past Papers").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(1) > .absolute").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border:nth-child(1) > .text-lg").click()
    time.sleep(3)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "View PDF").click()
    self.vars["win1371"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1371"])
  
