# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangePassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changePassword(self):
    self.driver.get("https://sproj-prototype1.vercel.app/")
    self.driver.set_window_size(1536, 837)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("saad.khilji@hotmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("Saad2003@")
    self.driver.find_element(By.CSS_SELECTOR, ".py-3").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-teal-500:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bg-teal-500:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "current-password").click()
    self.driver.find_element(By.ID, "current-password").send_keys("Saad2003@")
    self.driver.find_element(By.ID, "new-password").click()
    self.driver.find_element(By.ID, "new-password").send_keys("Saad2003!")
    self.driver.find_element(By.CSS_SELECTOR, ".px-4:nth-child(3)").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.text_to_be_present_in_element((By.CSS_SELECTOR, ".message"), "Password changed successfully"))
  
